### ISSUE TITLE
Blueutil binary not working on silicon Macs

### ISSUE THREAD

**Issue by aymane-eljerari** [vegardinho/alfred_bluetooth_controller#35] opened 2023-02-11 00:34 UTC
I opened blueutil and notificator as shown in the installation guide, but I still can not interface with my bluetooth devices through alfred.

**Comment by aymane-eljerari** [comment] 2023-02-11 00:40
Running this command within the workflow directory 
```
xattr -d com.apple.quarantine ./blueutil
```

returns this

```
xattr: ./blueutil: No such xattr: com.apple.quarantine
```

**Comment by vegardinho** [comment] 2023-02-12 17:50
I'll need some debugging info if you want me to take a look at it. Your command line return indicates that there is no quarantine on that file, so the issue is somewhere else.

**Comment by aymane-eljerari** [comment] 2023-02-13 16:05
Yes, how can I provide the debugging info? Is there a log file somewhere?

**Comment by vegardinho** [comment] 2023-02-13 16:30
Take a screenshot from the outout of the [Workflow Debugger](https://www.alfredapp.com/help/workflows/advanced/debugger/)

**Comment by aymane-eljerari** [comment] 2023-02-13 22:31
This is what the debugger shows, when I run bton. Is the Bluetooth controller compatible with apple silicon?

<img width="855" alt="Screenshot 2023-02-13 at 5 30 28 PM" src="https://user-images.githubusercontent.com/80056290/218589284-ce8e4727-920e-481b-8124-f230bbe2ec18.png">

**Comment by vegardinho** [comment] 2023-02-15 09:24
Might be that I accidentally removed cross compatibility in the last update. Try to replace the blueutil binary file with the one below (or install the alternative workflow, also below; in that case, the commands for on/off are 'btw' and 'bty'), and see if that fixes it.

Edit: I have to ask you to do it, because I don't have a computer with apple silicon myself.
[Archivo comprimido.zip](https://github.com/vegardinho/alfred_bluetooth_controller/files/10741444/Archivo.comprimido.zip)

**Comment by JSFLJ** [comment] 2023-09-07 15:13
@vegardinho the above file still does not fix this issue on apple silicon. I am having this exact same issue. 

I used your alternative workflow (in the zip file).

**Comment by vegardinho** [comment] 2023-09-10 10:43
Can you try this workflow? Make sure to delete or rename the commands of the old workflow first.
[Bluetooth Controller Beta.zip](https://github.com/vegardinho/alfred_bluetooth_controller/files/12568013/Bluetooth.Controller.Beta.zip)

**Comment by JSFLJ** [comment] 2023-09-19 23:22
Hi @vegardinho, unfortunately that did not solve my problem. Still getting the following issue in the debugger. 

[19:19:55.075] Logging Started...
[19:19:59.115] Bluetooth Controller Beta[Script Filter] Queuing argument '(null)'
[19:19:59.213] Bluetooth Controller Beta[Script Filter] Script with argv '(null)' finished
[19:19:59.217] ERROR: Bluetooth Controller Beta[Script Filter] Code 1: security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
Traceback (most recent call last):
  File "../Alfred.alfredpreferences/workflows/user.workflow.C9093872-1204-4C4D-82EF-6A073DE4A8CC/./scripts/return_device_json.py", line 137, in <module>
    main()
  File "../Alfred.alfredpreferences/workflows/user.workflow.C9093872-1204-4C4D-82EF-6A073DE4A8CC/./scripts/return_device_json.py", line 39, in main
    js_bytes = check_output(cmd_args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 86] Bad CPU type in executable: './blueutil'

**Comment by vegardinho** [comment] 2023-09-21 19:27
Can you try running the binary below directly? 

`cd ~/Downloads/blueutil` (or wherever you unzip the file)
`./blueutil --paired`

Does it run as expected?

Also, if you could install blueutil with homebrew/macports/other and send me the installed version (check where it is by running `whereis blueutil`), that would be great.

[blueutil.zip](https://github.com/vegardinho/alfred_bluetooth_controller/files/12690921/blueutil.zip)

**Comment by JSFLJ** [comment] 2023-09-29 12:36
After running the terminal commands, I get; 
`zsh: bad CPU type in executable: ./blueutil`

For blueutil version; 
blueutil -v
2.9.1

Looking forward to solving this issue.

**Comment by vegardinho** [comment] 2024-01-03 12:06
@JSFLJ Could you also do this?

> Also, if you could install blueutil with homebrew/macports/other and send me the installed version (check where it is by running whereis blueutil), that would be great.

Essentially, I'm trying to figure out whether the binary provided by homebrew/macports is [universal](https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary) or targeted against specific architecture (apple chip/intel).

**Comment by JSFLJ** [comment] 2024-01-10 16:16
I will do this in a few weeks and let you know.


On Wed, Jan 03, 2024 at 7:06 AM, vegardinho ***@***.******@***.***>> wrote:
You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

@JSFLJ<https://github.com/JSFLJ> Could you also do this?

Also, if you could install blueutil with homebrew/macports/other and send me the installed version (check where it is by running whereis blueutil), that would be great.

Essentially, I'm trying to figure out whether the binary provided by homebrew/macports is universal<https://developer.apple.com/documentation/apple-silicon/building-a-universal-macos-binary> or targeted against specific architecture (apple chip/intel).

**Comment by rh10hd** [comment] 2024-07-19 10:03
> Can you try this workflow? Make sure to delete or rename the commands of the old workflow first. [Bluetooth Controller Beta.zip](https://github.com/vegardinho/alfred_bluetooth_controller/files/12568013/Bluetooth.Controller.Beta.zip)

This beta version works well on Sonoma 14.5, M1 Chip. Thank you for making this workflow🥳
![btsetfavorite](https://github.com/user-attachments/assets/67a04024-47b6-4a30-ad1e-95445fd5b2e9)

**Comment by JSFLJ** [comment] 2024-07-26 17:52
@rh10hd could you please tell me step-by-step how you did it please? 

> > Can you try this workflow? Make sure to delete or rename the commands of the old workflow first. [Bluetooth Controller Beta.zip](https://github.com/vegardinho/alfred_bluetooth_controller/files/12568013/Bluetooth.Controller.Beta.zip)
> 
> This beta version works well on Sonoma 14.5, M1 Chip. Thank you for making this workflow🥳

**Comment by rh10hd** [comment] 2024-07-27 05:34
> @rh10hd could you please tell me step-by-step how you did it please?
> 
> > > Can you try this workflow? Make sure to delete or rename the commands of the old workflow first. [Bluetooth Controller Beta.zip](https://github.com/vegardinho/alfred_bluetooth_controller/files/12568013/Bluetooth.Controller.Beta.zip)
> > 
> > 
> > This beta version works well on Sonoma 14.5, M1 Chip. Thank you for making this workflow🥳

@JSFLJ 
I deleted the older version, downloaded the beta version and followed the [Installation](https://github.com/vegardinho/alfred_bluetooth_controller?tab=readme-ov-file#installation) step by step. You can [check the dependencies in Alfred preferences](https://www.alfredapp.com/help/kb/dependencies/) after installing the workflow. I guess that might help a bit.

Don't forget to [allow Alfred to have access to bluetooth](https://github.com/vegardinho/alfred_bluetooth_controller?tab=readme-ov-file#allow-alfred-to-control-bluetooth). That's the point, I found that it was this step that caused the workflow to not work. Once I opened the setting, the workflow worked immediately!

BTW, when you try to [Remove quarantine using terminal](https://github.com/vegardinho/alfred_bluetooth_controller?tab=readme-ov-file#remove-quarantine-using-terminal) for `blueutil` or `notificator`, it may return `xattr: ./blueutil: No such xattr: com.apple.quarantine`. Don't worry, I tried several times and the same thing happened. Just make sure you've installed both of them as required.

I hope this would help you.

**Comment by JSFLJ** [comment] 2024-07-27 22:16
That helped! THANK YOU! ITS WORKING NOW 😄
________________________________

**Comment by vegardinho** [comment] 2024-07-28 14:20
Thanks, @rh10hd! And I'm glad you got it working, @JSFLJ!

I've now created a new version that relies on Homebrew installation through Alfred's 'Resolve Dependencies' feature. That should therefore rid any problems with architecture!'

There is one caveat, though: I'm not sure if this version too requires manual removal of quarantine. Could you test this beta to see if it works automatically, once you've run 'Resolve Dependencies', or if you get an error because `blueutil` must be allowed to run? Remember to delete the current version first.

If this version also requires manual removal of quarantine, I'm not sure I'll implement it, as there'll be too many installation steps.
[Bluetooth Controller Beta 4.0.2.zip](https://github.com/user-attachments/files/16404038/Bluetooth.Controller.Beta.4.0.2.zip)

**Comment by rh10hd** [comment] 2024-07-29 01:17
> Thanks, @rh10hd! And I'm glad you got it working, @JSFLJ!
> 
> I've now created a new version that relies on Homebrew installation through Alfred's 'Resolve Dependencies' feature. That should therefore rid any problems with architecture!'
> 
> There is one caveat, though: I'm not sure if this version too requires manual removal of quarantine. Could you test this beta to see if it works automatically, once you've run 'Resolve Dependencies', or if you get an error because `blueutil` must be allowed to run? Remember to delete the current version first.
> 
> If this version also requires manual removal of quarantine, I'm not sure I'll implement it, as there'll be too many installation steps. [Bluetooth Controller Beta 4.0.2.zip](https://github.com/user-attachments/files/16404038/Bluetooth.Controller.Beta.4.0.2.zip)

 (I’m not an English native speaker, some words and grammars might be used incorrectly, so I hope this does not cause you any misunderstanding or inconvenience.)

Hi @vegardinho . Wow! Thanks for updating the workflow!! I became the lucky one to have a try on the new beta version😉I installed it as soon as I received your mail, it worked well on my Mac! I didn’t even resolve the dependencies in Alfred preferences. So I think the problem is that the Alfred doesn’t have the access to Bluetooth. Giving Alfred the permission to control the Bluetooth is not mandatory so lots of people would not do that lol.

Nevertheless I have to say that I’ve installed `bluetil` on the previous beta version so I’m not sure that whether this would affect the new beta version.


Moreover,  in the course of using this workflow, I’ve met 2 bugs. First, when I `toggled connection with Bluetooth device`, some devices displayed the previous name (I’ve used those names before) but the names on `BLUETOOTH STATUS` were normal. It ‘s a bit annoying, but it doesn’t bother me much. 

Second, when I tried to `toggle/reset the Bluetooth status`, the list filter didn’t show up. I had to press the right arrow button to use the Universal Action and then press Escape. I’m sorry that I can’t reproduce the problem, but I’ve found [the solution](https://www.alfredforum.com/topic/19039-list-filter-no-longer-launching/) on the Alfred forum, hope that you could improve it in the next version.

Regardless, the new beta version is BRILLIANT even though there are a few minor issues. Thanks again!

**Comment by vegardinho** [comment] 2024-07-29 21:04
Thanks for the feedback, @rh10hd!

Maybe you're right that allowing Alfred to manage bluetooth is sufficient! Still, I'm not comfortable ruling out the possibility of it not being enough – besides, what about the notifcator binary? I assume Alfred is already allowed to post notifications? The fact that you were able to run homebrew-blueutil without allowing it specifically, though, is promising!

I think I've fixed the bug related to the confirmation, using your suggestion. Try installing the beta below to see if you still get the same problem behavior as before.

The device names is not really something I've changed in the latest releases, so it's not really related to this beta. If you continue to get old names, feel free to create a new issue! If you are able to first reproduce the error on a different computer, to rule out your computer being the error source, that would be great – but feel free to post the issue either way.
[Bluetooth Controller Beta v4.1.zip](https://github.com/user-attachments/files/16419077/Bluetooth.Controller.Beta.v4.1.zip)

**Comment by rh10hd** [comment] 2024-07-30 13:44
Thanks!! @vegardinho 
 I forgot to mention the notificator, because it has been working well on my Mac since I first installed the workflow. So is now! I can control it on systems setting's notication directly. The new version works fine, although the names of some of devices are still problematic, but I've put them behind me (as they don't affect normal use) 
Thank you for developing and maintaining this workflow. I love it!

**Comment by vegardinho** [comment] 2024-07-30 20:57
Now pushed [v4.2](https://github.com/vegardinho/alfred_bluetooth_controller/releases/tag/4.2). Closing this issue.

**Closed as completed by vegardinho** 2024-07-30 20:57 UTC
