### ISSUE TITLE
Btc not working on Mac Sonoma

### ISSUE THREAD

**Issue by jamie9090** [vegardinho/alfred_bluetooth_controller#37] opened 2023-10-23 05:54 UTC
Was loving this workflow, but now in Mac Sonoma, BT controls aren't working anymore - just no devices are showing up! Straight to fall back.

**Comment by vegardinho** [comment] 2023-10-24 12:55
I can only reproduce the error inside the alfred environment, so there might be a bug with Alfred. It works when I run `return_device_json.py` manually. If anyone has any suggestions, feel free to try and fix the problem or hit me up. I'll paste the error I get in Alfred:

```File "/Users/<username>/Alfred.alfredpreferences/workflows/user.workflow.8BEDA4A2-A978-46D5-A9A3-05A8EDCD61C7/./scripts/return_device_json.py", line 137, in <module>
    main()
  File "/Users/<username>/Alfred.alfredpreferences/workflows/user.workflow.8BEDA4A2-A978-46D5-A9A3-05A8EDCD61C7/./scripts/return_device_json.py", line 39, in main
    js_bytes = check_output(cmd_args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./blueutil', '--format', 'json', '--paired']' died with <Signals.SIGABRT: 6>.```

**Comment by n-eagle-eye** [comment] 2023-11-06 13:08
Hello guys, 
I have the same issue, which happened after updating to Sonoma. I wonder if there is any chance of getting this fixed.

**Comment by tdrayson** [comment] 2023-11-08 11:53
Came here to see if there was a fix for this workflow for Sonoma, after some digging, I found a closed issue which explained how to get it working - https://github.com/vegardinho/alfred_bluetooth_controller/issues/36

### Solution: 
Add the bluetooth permission to Alfred in System setting -> security -> bluetooth.

Hope this helps 😃

**Comment by vegardinho** [comment] 2023-11-09 09:29
Thanks, @tdrayson! I think I discarded the issue because it was closed right after it was opened, and I just assumed it was a non-issue. Will update README.

**Closed as completed by vegardinho** 2023-11-09 09:29 UTC

**Comment by vegardinho** [comment] 2023-11-09 09:51
Added to README 7539afc40b3daea3e5e3fdb8c9b56cfd8cee5ba8.
